-- CREATE DATABASE
CREATE DATABASE AUTOFORM;

-- CREATE TABLES
CREATE TABLE RANGER_INFO (
    RangerID int NOT NULL,
    RangerFirst varchar(50),
    RangerLast varchar(50),
    RangerMI char(1),
    RangerDODID int(10),
    RangerRank varchar(5),
    RangerOther varchar(255),
    PRIMARY KEY (RangerID)
);
CREATE TABLE FORMS (

);
CREATE TABLE EQUIPMENT_BII (
    UUID int NOT NULL,
    ITEM_NSN int(13),
    SERIAL_NUMBER varchar(50),
    ITEM_DESCRIPTION varchar(255),
    ITEM_QUANTITY int,
    PRIMARY KEY (UUID)
);

CREATE TABLE EQUIPMENT_END_ITEM (
    UUID INT PRIMARY KEY NOT NULL,
    ITEM_NSN int(13),
    SERIAL_NUMBER VARCHAR(50),
    ITEM_DESCRIPTION VARCHAR(255),
    ASSOCIATED_BII VARCHAR(255),
    ITEM_QUANTITY INT,
    PRIMARY KEY (UUID)
)
